// apps/solid/src/sidebar/collections/create-collection-modal.tsx
import { createCollectionOptions } from '@colette/query'
import { useNavigate } from '@solidjs/router'
import { createForm } from '@tanstack/solid-form'
import { createMutation, useQueryClient } from '@tanstack/solid-query'
import Plus from 'lucide-solid/icons/plus'
import { type Component, createSignal } from 'solid-js'
import { z } from 'zod'
import { Button } from '~/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '~/components/ui/dialog'
import { SidebarGroupAction } from '~/components/ui/sidebar'
import {
  TextField,
  TextFieldErrorMessage,
  TextFieldInput,
  TextFieldLabel,
} from '~/components/ui/text-field'
import { useAPI } from '~/lib/api-context'

export const CreateCollectionModal: Component = () => {
  const api = useAPI()
  const navigate = useNavigate()
  const queryClient = useQueryClient()

  const [open, setOpen] = createSignal(false)

  const form = createForm(() => ({
    defaultValues: {
      title: '',
    },
    onSubmit: ({ value }) => mutation.mutate(value),
  }))

  const mutation = createMutation(() =>
    createCollectionOptions(api, queryClient, {
      onSuccess: (collection) => {
        form.reset()
        setOpen(false)

        navigate(`/collections/${collection.id}`)
      },
    }),
  )

  return (
    <Dialog open={open()} onOpenChange={setOpen}>
      <DialogTrigger as={SidebarGroupAction}>
        <Plus />
      </DialogTrigger>
      <DialogContent class="gap-6">
        <DialogHeader>
          <DialogTitle>Add Collection</DialogTitle>
          <DialogDescription>
            Create a new collection of bookmarks.
          </DialogDescription>
        </DialogHeader>
        <form
          onSubmit={(e) => {
            e.preventDefault()
            form.handleSubmit()
          }}
        >
          <form.Field
            name="title"
            validators={{
              onSubmit: z.string().min(1, 'Title cannot be empty'),
            }}
          >
            {(field) => (
              <TextField
                class="grow space-y-1"
                value={field().state.value}
                onChange={field().handleChange}
                validationState={
                  field().state.meta.errors.length > 0 ? 'invalid' : 'valid'
                }
              >
                <TextFieldLabel>Title</TextFieldLabel>
                <TextFieldInput />
                <TextFieldErrorMessage>
                  {field().state.meta.errors[0]?.toString()}
                </TextFieldErrorMessage>
              </TextField>
            )}
          </form.Field>
          <DialogFooter class="mt-6">
            <Button type="submit" disabled={mutation.isPending}>
              Submit
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}

// apps/web/src/sidebar/library/collections/create-collection-modal.tsx
import { useCreateCollectionMutation } from '@colette/query'
import { useForm } from '@tanstack/react-form'
import { Plus } from 'lucide-react'
import { type FC, useState } from 'react'
import { navigate } from 'wouter/use-browser-location'
import { z } from 'zod'
import { FormMessage } from '~/components/form'
import { Button } from '~/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '~/components/ui/dialog'
import { Input } from '~/components/ui/input'
import { Label } from '~/components/ui/label'
import { SidebarGroupAction } from '~/components/ui/sidebar'

export const CreateCollectionModal: FC = () => {
  const [isOpen, setOpen] = useState(false)

  const form = useForm({
    defaultValues: {
      title: '',
    },
    onSubmit: ({ value }) =>
      createCollection.mutate(value, {
        onSuccess: (collection) => {
          form.reset()
          setOpen(false)

          navigate(`/collections/${collection.id}`)
        },
      }),
  })

  const createCollection = useCreateCollectionMutation()

  return (
    <Dialog open={isOpen} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <SidebarGroupAction>
          <Plus />
        </SidebarGroupAction>
      </DialogTrigger>
      <DialogContent className="gap-6">
        <DialogHeader>
          <DialogTitle>Add Collection</DialogTitle>
          <DialogDescription>
            Create a new collection of bookmarks.
          </DialogDescription>
        </DialogHeader>
        <form
          onSubmit={(e) => {
            e.preventDefault()
            form.handleSubmit()
          }}
        >
          <form.Field
            name="title"
            validators={{
              onSubmit: z.string().min(1, 'Title cannot be empty'),
            }}
          >
            {(field) => (
              <div className="space-y-1">
                <Label>Title</Label>
                <Input
                  value={field.state.value}
                  onChange={(ev) => field.handleChange(ev.target.value)}
                />
                <FormMessage>
                  {field.state.meta.errors[0]?.toString()}
                </FormMessage>
              </div>
            )}
          </form.Field>
          <DialogFooter className="mt-6">
            <Button type="submit" disabled={createCollection.isPending}>
              Submit
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
