// packages/react-ui/src/components/form.tsx
import type { ComponentPropsWithRef, FC } from 'react'
import { cn } from '~/lib/utils'

const FormDescription: FC<ComponentPropsWithRef<'p'>> = ({
  className,
  ...props
}) => {
  return (
    <p className={cn('text-muted-foreground text-sm', className)} {...props} />
  )
}
FormDescription.displayName = 'FormDescription'

const FormMessage: FC<ComponentPropsWithRef<'p'>> = ({
  className,
  children,
  ...props
}) => {
  if (!children) return null

  return (
    <p
      className={cn('text-destructive text-sm font-medium', className)}
      {...props}
    >
      {children}
    </p>
  )
}
FormMessage.displayName = 'FormMessage'

export { FormDescription, FormMessage }

// apps/solid/src/lib/components/form.tsx
import { Field } from '@ark-ui/solid'
import { type Component, splitProps } from 'solid-js'
import { cn } from '~/lib/utils'

export const FormControl: Component<Field.RootProps> = (props) => {
  return <Field.Root {...props} />
}

export const FormMessage: Component<Field.ErrorTextProps> = (props) => {
  const [local, others] = splitProps(props, ['class'])

  return (
    <Field.ErrorText
      class={cn('font-medium text-destructive text-sm', local.class)}
      {...others}
    />
  )
}
