// packages/ui/lib/separator.tsx
import { cn } from './utils'
import { HTMLArkProps, ark } from '@ark-ui/react'

export type SeparatorProps = HTMLArkProps<'div'> & {
  orientation?: 'vertical' | 'horizontal'
  decorative?: boolean
}

export const Separator = ({
  className,
  orientation = 'horizontal',
  decorative = true,
  ...props
}: SeparatorProps) => {
  const semanticProps = decorative
    ? { role: 'none' }
    : {
        'aria-orientation':
          orientation === 'vertical' ? orientation : undefined,
        role: 'separator',
      }

  return (
    <ark.div
      data-scope="separator"
      data-orientation={orientation}
      className={cn(
        'bg-border shrink-0 data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px',
        className,
      )}
      {...semanticProps}
      {...props}
    />
  )
}

// apps/solid/src/lib/components/separator.tsx
import { type HTMLArkProps, ark } from '@ark-ui/solid'
import { type Component, mergeProps, splitProps } from 'solid-js'

export type SeparatorProps = HTMLArkProps<'hr'> & {
  orientation?: 'horizontal' | 'vertical'
}

export const Separator: Component<SeparatorProps> = (props) => {
  const mergedProps = mergeProps(
    { orientation: 'horizontal' } as SeparatorProps,
    props,
  )

  const [local, others] = splitProps(mergedProps, ['orientation'])

  return (
    <ark.hr
      aria-orientation={local.orientation}
      data-orientation={local.orientation}
      {...others}
    />
  )
}
