// apps/solid/src/lib/components/field.tsx
import { Field } from '@ark-ui/solid'
import { type Component, splitProps } from 'solid-js'
import { cn } from '../utils'
import { cva } from 'class-variance-authority'

export const Root: Component<Field.RootProps> = (props) => {
  return <Field.Root {...props} />
}

export const Input: Component<Field.InputProps> = (props) => {
  const [local, rest] = splitProps(props, ['class'])

  return (
    <Field.Input
      class={cn(
        'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-base ring-offset-background file:border-0 file:bg-transparent file:font-medium file:text-foreground file:text-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
        local.class,
      )}
      {...rest}
    />
  )
}

export const labelVariants = cva(
  'font-medium text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
)

export const Label: Component<Field.LabelProps> = (props) => {
  const [local, rest] = splitProps(props, ['class'])

  return <Field.Label class={cn(labelVariants(), local.class)} {...rest} />
}

export const ErrorText: Component<Field.ErrorTextProps> = (props) => {
  const [local, rest] = splitProps(props, ['class'])

  return (
    <Field.ErrorText
      class={cn('font-medium text-destructive text-sm', local.class)}
      {...rest}
    />
  )
}

// packages/ui/lib/field.tsx
import { cn } from './utils'
import { Field } from '@ark-ui/react'

export type RootProps = Field.RootProps

export const Root = Field.Root

export type InputProps = Field.InputProps

export const Input = ({ className, ...props }: InputProps) => {
  return (
    <Field.Input
      className={cn(
        'file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input flex h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
        'focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]',
        'aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive',
        className,
      )}
      {...props}
    />
  )
}

export type LabelProps = Field.LabelProps

export const Label = ({ className, ...props }: LabelProps) => {
  return (
    <Field.Label
      className={cn(
        'flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
        className,
      )}
      {...props}
    />
  )
}

export type ErrorTextProps = Field.ErrorTextProps

export const ErrorText = ({
  className,
  children,
  ...props
}: ErrorTextProps) => {
  if (!children) return null

  return (
    <Field.ErrorText
      className={cn('text-destructive text-sm', className)}
      {...props}
    >
      {children}
    </Field.ErrorText>
  )
}

export type HelperTextProps = Field.HelperTextProps

export const HelperText = ({ className, ...props }: HelperTextProps) => {
  return (
    <Field.HelperText
      className={cn('text-muted-foreground text-sm', className)}
      {...props}
    />
  )
}
