// apps/web/src/sidebar/library/collections/collection-item.tsx
import { DeleteCollectionAlert } from './delete-collection-alert'
import type { Collection } from '@colette/core'
import { Library, MoreHorizontal } from 'lucide-react'
import { type FC, useState } from 'react'
import { Link, useRoute } from 'wouter'
import { SidebarMenuSubAction } from '~/components/sidebar-menu-sub-action'
import { AlertDialog, AlertDialogTrigger } from '~/components/ui/alert-dialog'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '~/components/ui/dropdown-menu'
import {
  SidebarMenuSubButton,
  SidebarMenuSubItem,
} from '~/components/ui/sidebar'

export const CollectionItem: FC<{ collection: Collection }> = (props) => {
  const [match, params] = useRoute('/collections/:id')

  const [isOpen, setOpen] = useState(false)

  return (
    <SidebarMenuSubItem>
      <SidebarMenuSubButton
        asChild
        isActive={match && props.collection.id === params?.id}
      >
        <Link to={`/collections/${props.collection.id}`}>
          <Library className="text-primary" />
          <span className="line-clamp-1">{props.collection.title}</span>
        </Link>
      </SidebarMenuSubButton>
      <AlertDialog open={isOpen} onOpenChange={setOpen}>
        <DropdownMenu modal={false}>
          <DropdownMenuTrigger asChild>
            <SidebarMenuSubAction showOnHover>
              <MoreHorizontal />
            </SidebarMenuSubAction>
          </DropdownMenuTrigger>
          <DropdownMenuContent side="right">
            <AlertDialogTrigger asChild>
              <DropdownMenuItem>Delete</DropdownMenuItem>
            </AlertDialogTrigger>
          </DropdownMenuContent>
        </DropdownMenu>
        <DeleteCollectionAlert
          collection={props.collection}
          close={() => setOpen(false)}
        />
      </AlertDialog>
    </SidebarMenuSubItem>
  )
}

// apps/solid/src/sidebar/collections/collection-item.tsx
import type { Collection } from '@colette/core'
import { A } from '@solidjs/router'
import Library from 'lucide-solid/icons/library'
import MoreHorizontal from 'lucide-solid/icons/more-horizontal'
import { type Component, createSignal } from 'solid-js'
import { AlertDialog, AlertDialogTrigger } from '~/components/ui/alert-dialog'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '~/components/ui/dropdown-menu'
import {
  SidebarMenuAction,
  SidebarMenuButton,
  SidebarMenuItem,
} from '~/components/ui/sidebar'
import { DeleteCollectionAlert } from './delete-collection-alert'

export const CollectionItem: Component<{ collection: Collection }> = (
  props,
) => {
  const [isAlertOpen, setAlertOpen] = createSignal(false)

  return (
    <SidebarMenuItem>
      <SidebarMenuButton as={A} href={`/collections/${props.collection.id}`}>
        <Library class="text-orange-500" />
        {props.collection.title}
      </SidebarMenuButton>
      <AlertDialog open={isAlertOpen()} onOpenChange={setAlertOpen}>
        <DropdownMenu placement="right-start">
          <DropdownMenuTrigger as={SidebarMenuAction<'button'>}>
            <MoreHorizontal />
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <AlertDialogTrigger as={DropdownMenuItem<'div'>}>
              Delete
            </AlertDialogTrigger>
          </DropdownMenuContent>
        </DropdownMenu>
        <DeleteCollectionAlert
          collection={props.collection}
          close={() => setAlertOpen(false)}
        />
      </AlertDialog>
    </SidebarMenuItem>
  )
}
