// apps/web/src/sidebar/library/collections/delete-collection-alert.tsx
import type { Collection } from '@colette/core'
import { useDeleteCollectionMutation } from '@colette/query'
import type { FC } from 'react'
import { useParams } from 'wouter'
import { navigate } from 'wouter/use-browser-location'
import {
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogTitle,
} from '~/components/ui/alert-dialog'

export const DeleteCollectionAlert: FC<{
  collection: Collection
  close: () => void
}> = (props) => {
  const params = useParams<{ id?: string }>()

  const deleteCollection = useDeleteCollectionMutation(props.collection.id)

  return (
    <AlertDialogContent>
      <AlertDialogTitle>
        Delete <span className="text-primary">{props.collection.title}</span>
      </AlertDialogTitle>
      <AlertDialogDescription>
        Are you sure you want to delete this collection and all of its
        bookmarks? This action cannot be undone.
      </AlertDialogDescription>
      <AlertDialogFooter>
        <AlertDialogCancel>Cancel</AlertDialogCancel>
        <AlertDialogAction
          disabled={deleteCollection.isPending}
          onClick={() =>
            deleteCollection.mutate(undefined, {
              onSuccess: () => {
                props.close()

                if (params.id === props.collection.id) {
                  navigate('/collections')
                }
              },
            })
          }
        >
          Confirm
        </AlertDialogAction>
      </AlertDialogFooter>
    </AlertDialogContent>
  )
}

// apps/solid/src/sidebar/collections/delete-collection-alert.tsx
import type { Collection } from '@colette/core'
import { deleteCollectionOptions } from '@colette/query'
import { useNavigate, useParams } from '@solidjs/router'
import { createMutation, useQueryClient } from '@tanstack/solid-query'
import type { Component } from 'solid-js'
import {
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogTitle,
} from '~/components/ui/alert-dialog'
import { Button } from '~/components/ui/button'
import { DialogFooter } from '~/components/ui/dialog'
import { useAPI } from '~/lib/api-context'

export const DeleteCollectionAlert: Component<{
  collection: Collection
  close: () => void
}> = (props) => {
  const api = useAPI()
  const navigate = useNavigate()
  const params = useParams<{ id?: string }>()
  const queryClient = useQueryClient()

  const mutation = createMutation(() =>
    deleteCollectionOptions(props.collection.id, api, queryClient, {
      onSuccess: () => {
        props.close()

        if (params.id === props.collection.id) {
          navigate('/collections')
        }
      },
    }),
  )

  return (
    <AlertDialogContent>
      <AlertDialogTitle>
        Delete <span class="text-orange-500">{props.collection.title}</span>
      </AlertDialogTitle>
      <AlertDialogDescription>
        Deleting a collection also deletes all bookmarks within the collection.
        Are you sure you want to delete this collection? This action cannot be
        undone.
      </AlertDialogDescription>
      <DialogFooter>
        <Button variant="outline" onClick={() => props.close()}>
          Close
        </Button>
        <Button disabled={mutation.isPending} onClick={() => mutation.mutate()}>
          Confirm
        </Button>
      </DialogFooter>
    </AlertDialogContent>
  )
}
