// packages/app/lib/routes/collections/id.tsx
import { BookmarkGrid } from '../bookmarks/components/bookmark-grid'
import { getCollectionOptions, listBookmarksOptions } from '@colette/query'
import { getRouteApi } from '@colette/router'
import { Button, Dialog } from '@colette/ui'
import { useAPI } from '@colette/util'
import { useInfiniteQuery, useQuery } from '@tanstack/react-query'
import { Pencil, Trash2 } from 'lucide-react'
import { useEffect } from 'react'

const routeApi = getRouteApi('/layout/collections/$collectionId')

export const CollectionPage = () => {
  const api = useAPI()
  const params = routeApi.useParams()

  const collectionQuery = useQuery(
    getCollectionOptions(api, params.collectionId),
  )
  const bookmarksQuery = useInfiniteQuery(
    listBookmarksOptions(api, {
      collectionId: params.collectionId,
    }),
  )

  useEffect(() => {
    window.scrollTo(0, 0)
  }, [params.collectionId])

  if (!collectionQuery.data) return

  if (
    collectionQuery.isLoading ||
    !collectionQuery.data ||
    bookmarksQuery.isLoading ||
    !bookmarksQuery.data
  )
    return

  return (
    <>
      <div className="bg-background sticky top-0 z-10 flex justify-between p-8">
        <h1 className="line-clamp-1 text-3xl font-medium">
          {collectionQuery.data.title}
        </h1>
        <div className="flex gap-2">
          <Dialog.Root>
            <Dialog.Trigger asChild>
              <Button variant="secondary">
                <Pencil />
                Edit
              </Button>
            </Dialog.Trigger>
          </Dialog.Root>
          <Dialog.Root>
            <Dialog.Trigger asChild>
              <Button variant="destructive">
                <Trash2 />
                Delete
              </Button>
            </Dialog.Trigger>
          </Dialog.Root>
        </div>
      </div>
      <main>
        <BookmarkGrid
          bookmarks={bookmarksQuery.data.pages.flatMap((page) => page.data)}
          hasMore={bookmarksQuery.hasNextPage}
          fetchMore={bookmarksQuery.fetchNextPage}
        />
      </main>
    </>
  )
}

// apps/solid/src/routes/collections/id.tsx
import { BookmarkGrid } from './bookmark-grid'
import { getCollectionOptions } from '@colette/query'
import { useParams } from '@solidjs/router'
import { createQuery } from '@tanstack/solid-query'
import BookmarkPlus from 'lucide-solid/icons/bookmark-plus'
import CircleX from 'lucide-solid/icons/circle-x'
import Pencil from 'lucide-solid/icons/pencil'
import { type Component, Show } from 'solid-js'
import { Button } from '~/components/ui/button'
import { useAPI } from '~/lib/api-context'

export const CollectionPage: Component = () => {
  const params = useParams<{ id: string }>()

  const query = createQuery(() => getCollectionOptions(params.id, useAPI()))

  return (
    <Show when={query.data}>
      {(collection) => (
        <>
          <div class="bg-background sticky top-0 z-10 flex justify-between p-8">
            <h1 class="text-3xl font-medium">{collection().title}</h1>
            <div class="flex gap-2">
              <Button variant="secondary">
                <Pencil />
                Edit
              </Button>
              <Button variant="secondary">
                <BookmarkPlus />
                Add
              </Button>
              <Button variant="destructive">
                <CircleX />
                Delete
              </Button>
            </div>
          </div>
          <main>
            <BookmarkGrid collectionId={collection().id} />
          </main>
        </>
      )}
    </Show>
  )
}
