// apps/web/src/sidebar/library/feeds/create-form/create-feed-modal.tsx
import { EditStep } from './edit-step'
import { SearchStep } from './search-step'
import { SelectStep } from './select-step'
import type { FeedDetected, FeedProcessed } from '@colette/core'
import { Plus } from 'lucide-react'
import { type FC, useState } from 'react'
import { Dialog } from '~/components/dialog'
import { DialogTrigger } from '~/components/ui/dialog'
import { SidebarGroupAction } from '~/components/ui/sidebar'

enum Step {
  Search = 0,
  Select = 1,
  Edit = 2,
}

export const CreateFeedModal: FC = () => {
  const [step, setStep] = useState(Step.Search)
  const [detectedFeeds, setDetectedFeeds] = useState<FeedDetected[] | null>(
    null,
  )
  const [selectedFeed, setSelectedFeed] = useState<FeedProcessed | null>(null)

  return (
    <Dialog>
      {(close) => (
        <>
          <DialogTrigger asChild>
            <SidebarGroupAction>
              <Plus />
            </SidebarGroupAction>
          </DialogTrigger>
          {step === Step.Search && (
            <SearchStep
              onNext={(res) => {
                if (Array.isArray(res)) {
                  setDetectedFeeds(res)
                  setStep(Step.Select)
                } else {
                  setSelectedFeed(res)
                  setStep(Step.Edit)
                }
              }}
            />
          )}
          {step === Step.Select && detectedFeeds && (
            <SelectStep
              feeds={detectedFeeds}
              onNext={(feed) => {
                setSelectedFeed(feed)
                setStep(Step.Edit)
              }}
              onBack={() => setStep(Step.Search)}
            />
          )}
          {step === Step.Edit && selectedFeed && (
            <EditStep
              feed={selectedFeed}
              onClose={() => {
                close()

                setStep(Step.Search)
                setDetectedFeeds(null)
                setSelectedFeed(null)
              }}
              onBack={() => {
                setStep(detectedFeeds ? Step.Select : Step.Search)
              }}
            />
          )}
        </>
      )}
    </Dialog>
  )
}

// apps/solid/src/sidebar/feeds/create-form/create-feed-modal.tsx
import type { FeedDetected, FeedProcessed } from '@colette/core'
import Plus from 'lucide-solid/icons/plus'
import { type Component, Match, Show, Switch, createSignal } from 'solid-js'
import { Dialog, DialogContent, DialogTrigger } from '~/components/ui/dialog'
import { SidebarGroupAction } from '~/components/ui/sidebar'
import { EditStep } from './edit-step'
import { SearchStep } from './search-step'
import { SelectStep } from './select-step'

enum Step {
  Search = 0,
  Select = 1,
  Edit = 2,
}

export const CreateFeedModal: Component = () => {
  const [open, setOpen] = createSignal(false)
  const [step, setStep] = createSignal(Step.Search)
  const [detectedFeeds, setDetectedFeeds] = createSignal<FeedDetected[] | null>(
    null,
  )
  const [selectedFeed, setSelectedFeed] = createSignal<FeedProcessed | null>(
    null,
  )

  return (
    <Dialog open={open()} onOpenChange={setOpen}>
      <DialogTrigger as={SidebarGroupAction}>
        <Plus />
      </DialogTrigger>
      <DialogContent class="gap-6">
        <Switch>
          <Match when={step() === Step.Search}>
            <SearchStep
              onNext={(res) => {
                if (Array.isArray(res)) {
                  setDetectedFeeds(res)
                  setStep(Step.Select)
                } else {
                  setSelectedFeed(res)
                  setStep(Step.Edit)
                }
              }}
            />
          </Match>
          <Match when={step() === Step.Select}>
            <Show when={detectedFeeds()}>
              {(feeds) => (
                <SelectStep
                  feeds={feeds()}
                  onNext={(feed) => {
                    setSelectedFeed(feed)
                    setStep(Step.Edit)
                  }}
                  onBack={() => setStep(Step.Search)}
                />
              )}
            </Show>
          </Match>
          <Match when={step() === Step.Edit}>
            <Show when={selectedFeed()}>
              {(feed) => (
                <EditStep
                  feed={feed()}
                  onClose={() => {
                    setOpen(false)
                    setStep(Step.Search)
                    setDetectedFeeds(null)
                    setSelectedFeed(null)
                  }}
                  onBack={() => {
                    setStep(detectedFeeds() ? Step.Select : Step.Search)
                  }}
                />
              )}
            </Show>
          </Match>
        </Switch>
      </DialogContent>
    </Dialog>
  )
}
