// packages/web/src/main.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import './index.css'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

const router = createRouter({
	routeTree,
})

declare module '@tanstack/react-router' {
	interface Register {
		router: typeof router
	}
}

ReactDOM.createRoot(document.getElementById('root')!).render(
	<React.StrictMode>
		<RouterProvider router={router} />
	</React.StrictMode>,
)

// packages/solid-web/src/index.tsx
import { Route, Router } from '@solidjs/router'
import { render } from 'solid-js/web'
import './index.css'
import { Home } from './routes/home'
import { Login } from './routes/login'
import { Register } from './routes/register'

render(
	() => (
		<Router>
			<Route path="/login" component={Login} />
			<Route path="/register" component={Register} />
			<Route path="/" component={Home} />
		</Router>
	),
	document.getElementById('root')!,
)
