// apps/solid/src/feeds/entry-card.tsx
import type { FeedEntry } from '@colette/core'
import type { Component } from 'solid-js'
import { Favicon } from '~/components/favicon'
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from '~/components/ui/card'
import { Separator } from '~/components/ui/separator'
import { formatRelativeDate } from '~/lib/utils'

export const EntryCard: Component<{ entry: FeedEntry }> = (props) => {
  return (
    <Card class="flex h-[160px] overflow-hidden">
      <img
        class="aspect-video object-cover"
        src={
          props.entry.thumbnailUrl ?? 'https://placehold.co/320x180/black/black'
        }
        alt={props.entry.title}
        loading="lazy"
      />
      <div class="flex grow flex-col gap-0">
        <CardHeader class="py-0 pt-4">
          <CardTitle title={props.entry.title}>{props.entry.title}</CardTitle>
        </CardHeader>
        <CardContent class="pt-2 pb-4">
          {props.entry.description ? (
            <p class="line-clamp-2">{props.entry.description}</p>
          ) : (
            <p>No description.</p>
          )}
        </CardContent>
        <CardFooter class="justify-between py-0 pb-4">
          <div class="flex h-4 items-center gap-2 font-medium text-sm">
            <div class="flex items-center gap-2">
              <Favicon url={props.entry.link} />
              {props.entry.author && (
                <span class="truncate">{props.entry.author}</span>
              )}
            </div>
            <Separator orientation="vertical" />
            <span title={new Date(props.entry.publishedAt).toString()}>
              {formatRelativeDate(props.entry.publishedAt)}
            </span>
          </div>
        </CardFooter>
      </div>
    </Card>
  )
}

// apps/web/src/routes/subscriptions/components/entry-card.tsx
import type { SubscriptionEntryDetails } from '@colette/core'
import { formatRelativeDate } from '@colette/util'
import type { FC } from 'react'
import { Favicon } from '~/components/favicon'
import { Thumbnail } from '~/components/thumbnail'
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from '~/components/ui/card'
import { Separator } from '~/components/ui/separator'

export const EntryCard: FC<{ details: SubscriptionEntryDetails }> = (props) => {
  const entry = props.details.feedEntry!

  return (
    <Card className="flex h-[160px] overflow-hidden">
      <Thumbnail src={entry.thumbnailUrl ?? undefined} alt={entry.title} />
      <div className="flex grow flex-col gap-0">
        <CardHeader className="py-0 pt-4">
          <CardTitle title={entry.title}>{entry.title}</CardTitle>
        </CardHeader>
        <CardContent className="pt-2 pb-4">
          {entry.description ? (
            <p className="line-clamp-2">{entry.description}</p>
          ) : (
            <p>No description.</p>
          )}
        </CardContent>
        <CardFooter className="justify-between py-0 pb-4">
          <div className="flex h-4 items-center gap-2 text-sm font-medium">
            <Favicon url={entry.link} />
            {entry.author && <span className="truncate">{entry.author}</span>}
            <Separator orientation="vertical" />
            <span title={new Date(entry.publishedAt).toString()}>
              {formatRelativeDate(entry.publishedAt)}
            </span>
          </div>
        </CardFooter>
      </div>
    </Card>
  )
}
