// packages/app/src/sidebar/feeds/feed-list.tsx
import { listFeedsOptions } from '@colette/query'
import { useQuery } from '@tanstack/react-query'
import type { FC } from 'react'
import { useAPI } from '../../lib/api-context'
import { FeedItem } from './feed-item'

export const FeedList: FC = () => {
  const api = useAPI()

  const { data: feeds, isLoading } = useQuery(listFeedsOptions({}, api))

  if (isLoading || !feeds) return

  return feeds.data.map((feed) => <FeedItem key={feed.id} feed={feed} />)
}

// apps/solid/src/sidebar/feeds/feed-list.tsx
import { FeedItem } from './feed-item'
import { listFeedsOptions } from '@colette/query'
import { createQuery } from '@tanstack/solid-query'
import { type Component, For, Show } from 'solid-js'
import { useAPI } from '~/lib/api-context'

export const FeedList: Component = () => {
  const api = useAPI()

  const query = createQuery(() => listFeedsOptions({}, api))

  return (
    <Show when={query.data}>
      {(feeds) => (
        <For each={feeds().data}>{(item) => <FeedItem feed={item} />}</For>
      )}
    </Show>
  )
}
