// packages/app/src/routes/_private/feeds/-components/unsubscribe-alert.tsx
import type { Feed } from '@colette/core'
import { deleteFeedOptions } from '@colette/query'
import {
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@colette/react-ui/components/ui/alert-dialog'
import { useMutation } from '@tanstack/react-query'
import { useMatchRoute, useNavigate } from '@tanstack/react-router'
import { Route } from '../../feeds'

type Props = {
  feed: Feed
  close: () => void
}

export function UnsubscribeAlert({ feed, close }: Props) {
  const context = Route.useRouteContext()

  const navigate = useNavigate()

  const matchRoute = useMatchRoute()
  const params = matchRoute({ to: '/feeds/$id' })

  const { mutateAsync: unsubscribe, isPending } = useMutation(
    deleteFeedOptions(feed.id, context.api, {
      onSuccess: async () => {
        close()

        if (typeof params === 'object' && params.id === feed.id) {
          await navigate({
            to: '/feeds',
          })
        }

        await context.queryClient.invalidateQueries({
          queryKey: ['feeds'],
        })
      },
    }),
  )

  return (
    <AlertDialogContent className="max-w-md p-6">
      <AlertDialogHeader>
        <AlertDialogTitle className="line-clamp-1">
          Unsubscribe from {feed.title ?? feed.originalTitle}?
        </AlertDialogTitle>
        <AlertDialogDescription>
          Are you sure you want to unsubscribe? This action cannot be undone.
        </AlertDialogDescription>
      </AlertDialogHeader>
      <AlertDialogFooter className="mt-8">
        <AlertDialogCancel>Cancel</AlertDialogCancel>
        <AlertDialogAction onClick={() => unsubscribe()} disabled={isPending}>
          Submit
        </AlertDialogAction>
      </AlertDialogFooter>
    </AlertDialogContent>
  )
}

// apps/solid/src/sidebar/feeds/unsubscribe-alert.tsx
import type { Feed } from '@colette/core'
import { deleteFeedOptions } from '@colette/solid-query'
import { useNavigate, useParams } from '@solidjs/router'
import { createMutation, useQueryClient } from '@tanstack/solid-query'
import type { Component } from 'solid-js'
import {
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogTitle,
} from '~/components/ui/alert-dialog'
import { Button } from '~/components/ui/button'
import { DialogFooter } from '~/components/ui/dialog'
import { useAPI } from '~/lib/api-context'

export const UnsubscribeAlert: Component<{
  feed: Feed
  close: () => void
}> = (props) => {
  const api = useAPI()
  const navigate = useNavigate()
  const queryClient = useQueryClient()

  const params = useParams<{ id?: string }>()

  const mutation = createMutation(() =>
    deleteFeedOptions(props.feed.id, api, {
      onSuccess: async () => {
        props.close()

        if (params.id === props.feed.id) {
          navigate('/feeds')
        }

        await queryClient.invalidateQueries({
          queryKey: ['feeds'],
        })
      },
    }),
  )

  return (
    <AlertDialogContent>
      <AlertDialogTitle>
        Unsubscribe from{' '}
        <span class="text-orange-500">
          {props.feed.title ?? props.feed.originalTitle}
        </span>
      </AlertDialogTitle>
      <AlertDialogDescription>
        Are you sure you want to unsubscribe? This action cannot be undone.
      </AlertDialogDescription>
      <DialogFooter>
        <Button variant="outline" onClick={() => props.close()}>
          Close
        </Button>
        <Button disabled={mutation.isPending} onClick={() => mutation.mutate()}>
          Confirm
        </Button>
      </DialogFooter>
    </AlertDialogContent>
  )
}
