// apps/solid/src/sidebar/feeds/create-form/edit-step.tsx
import type { FeedProcessed } from '@colette/core'
import { createFeedOptions } from '@colette/query'
import { useNavigate } from '@solidjs/router'
import { createForm } from '@tanstack/solid-form'
import { createMutation, useQueryClient } from '@tanstack/solid-query'
import RotateCcw from 'lucide-solid/icons/rotate-ccw'
import type { Component } from 'solid-js'
import { z } from 'zod'
import { Button } from '~/components/ui/button'
import {
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '~/components/ui/dialog'
import {
  TextField,
  TextFieldErrorMessage,
  TextFieldInput,
  TextFieldLabel,
} from '~/components/ui/text-field'
import { useAPI } from '~/lib/api-context'

export const EditStep: Component<{
  feed: FeedProcessed
  onClose: () => void
  onBack: () => void
}> = (props) => {
  const api = useAPI()
  const navigate = useNavigate()
  const queryClient = useQueryClient()

  const form = createForm(() => ({
    defaultValues: {
      title: props.feed.title,
    },
    onSubmit: ({ value }) => {
      let title: string | undefined = value.title
      if (title === props.feed.title) {
        title = undefined
      }

      mutation.mutate({
        url: props.feed.link,
        title,
      })
    },
  }))

  const mutation = createMutation(() =>
    createFeedOptions(api, queryClient, {
      onSuccess: (feed) => {
        form.reset()
        props.onClose()

        navigate(`/feeds/${feed.id}`)
      },
    }),
  )

  return (
    <>
      <DialogHeader>
        <DialogTitle>Edit Feed</DialogTitle>
        <DialogDescription>
          Modify a feed's metadata before subscribing to it
        </DialogDescription>
      </DialogHeader>
      <form
        onSubmit={(e) => {
          e.preventDefault()
          form.handleSubmit()
        }}
      >
        <form.Field
          name="title"
          validators={{
            onSubmit: z.string().min(1, 'Title cannot be empty'),
          }}
        >
          {(field) => (
            <TextField
              class="grow space-y-1"
              value={field().state.value}
              onChange={field().handleChange}
              validationState={
                field().state.meta.errors.length > 0 ? 'invalid' : 'valid'
              }
            >
              <TextFieldLabel>Title</TextFieldLabel>
              <div class="flex gap-2">
                <TextFieldInput />
                <Button
                  variant="outline"
                  onClick={() => field().setValue(props.feed.title)}
                >
                  <RotateCcw />
                </Button>
              </div>
              <TextFieldErrorMessage>
                {field().state.meta.errors[0]?.toString()}
              </TextFieldErrorMessage>
            </TextField>
          )}
        </form.Field>
        <DialogFooter class="mt-6">
          <Button variant="outline" onClick={props.onBack}>
            Back
          </Button>
          <Button type="submit" disabled={mutation.isPending}>
            Submit
          </Button>
        </DialogFooter>
      </form>
    </>
  )
}

// apps/web/src/sidebar/library/feeds/create-form/edit-step.tsx
import type { FeedProcessed } from '@colette/core'
import { useCreateFeedMutation } from '@colette/query'
import { useForm } from '@tanstack/react-form'
import type { FC } from 'react'
import { navigate } from 'wouter/use-browser-location'
import { z } from 'zod'
import { FormMessage } from '~/components/form'
import { Button } from '~/components/ui/button'
import {
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '~/components/ui/dialog'
import { Input } from '~/components/ui/input'
import { Label } from '~/components/ui/label'

export const EditStep: FC<{
  feed: FeedProcessed
  onClose: () => void
  onBack: () => void
}> = (props) => {
  const form = useForm({
    defaultValues: {
      title: props.feed.title,
    },
    onSubmit: ({ value }) => {
      createdFeed.mutate(
        {
          url: props.feed.link,
          title: value.title,
        },
        {
          onSuccess: (feed) => {
            form.reset()
            props.onClose()

            navigate(`/feeds/${feed.id}`)
          },
        },
      )
    },
  })

  const createdFeed = useCreateFeedMutation()

  return (
    <>
      <DialogHeader>
        <DialogTitle>Edit Feed</DialogTitle>
        <DialogDescription>
          {"Modify a feed's metadata before subscribing to it"}
        </DialogDescription>
      </DialogHeader>
      <form
        onSubmit={(e) => {
          e.preventDefault()
          form.handleSubmit()
        }}
      >
        <form.Field
          name="title"
          validators={{
            onSubmit: z.string().min(1, 'Title cannot be empty'),
          }}
        >
          {(field) => (
            <div className="space-y-1">
              <Label>Title</Label>
              <div className="flex gap-2">
                <Input
                  value={field.state.value}
                  onChange={(ev) => field.handleChange(ev.target.value)}
                />
              </div>
              <FormMessage>
                {field.state.meta.errors[0]?.toString()}
              </FormMessage>
            </div>
          )}
        </form.Field>
        <DialogFooter className="mt-6">
          <Button variant="outline" onClick={props.onBack}>
            Back
          </Button>
          <Button type="submit" disabled={createdFeed.isPending}>
            Submit
          </Button>
        </DialogFooter>
      </form>
    </>
  )
}
