// apps/solid/src/sidebar/user-card.tsx
import type { User as AppUser } from '@colette/core'
import { logoutOptions } from '@colette/query'
import { createMutation, useQueryClient } from '@tanstack/solid-query'
import ChevronsUpDown from 'lucide-solid/icons/chevrons-up-down'
import User from 'lucide-solid/icons/user'
import type { Component } from 'solid-js'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '~/components/ui/dropdown-menu'
import {
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
} from '~/components/ui/sidebar'
import { useAPI } from '~/lib/api-context'

export const UserCard: Component<{ user: AppUser }> = ({ user }) => {
  const api = useAPI()
  const queryClient = useQueryClient()

  const mutation = createMutation(() => logoutOptions(api, queryClient))

  return (
    <SidebarMenu>
      <SidebarMenuItem>
        <DropdownMenu sameWidth>
          <DropdownMenuTrigger
            as={SidebarMenuButton<'button'>}
            size="lg"
            class="data-[expanded]:bg-sidebar-accent"
          >
            <div class="flex size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
              <User class="size-4" />
            </div>
            <span class="font-semibold">{user.email.split('@')[0]}</span>
            <ChevronsUpDown class="ml-auto" />
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem onSelect={mutation.mutate}>
              Logout
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </SidebarMenuItem>
    </SidebarMenu>
  )
}

// packages/app/lib/sidebar/user-card.tsx
import { useLogoutUserMutation } from '@colette/query'
import { getRouteApi } from '@colette/router'
import { Menu, Sidebar } from '@colette/ui'
import { ChevronsUpDown, User } from 'lucide-react'

const routeApi = getRouteApi('/layout')

export const UserCard = () => {
  const context = routeApi.useRouteContext()
  const navigate = routeApi.useNavigate()

  const logoutUser = useLogoutUserMutation()

  function onLogout() {
    logoutUser.mutate(undefined, {
      onSuccess: () => {
        navigate({
          to: '/login',
          state: {
            loggedOut: true,
          },
          replace: true,
        })
      },
    })
  }

  return (
    <Sidebar.Menu>
      <Sidebar.MenuItem>
        <Menu.Root positioning={{ sameWidth: true }}>
          <Menu.Trigger asChild>
            <Sidebar.MenuButton
              className="data-[expanded]:bg-sidebar-accent"
              size="lg"
            >
              <div className="bg-sidebar-primary text-sidebar-primary-foreground flex size-8 items-center justify-center rounded-lg">
                <User className="size-4" />
              </div>
              <span className="font-semibold">
                {context.user.email.split('@')[0]}
              </span>
              <ChevronsUpDown className="ml-auto" />
            </Sidebar.MenuButton>
          </Menu.Trigger>
          <Menu.Content>
            <Menu.Item value="logout" onSelect={onLogout}>
              Logout
            </Menu.Item>
          </Menu.Content>
        </Menu.Root>
      </Sidebar.MenuItem>
    </Sidebar.Menu>
  )
}
