// apps/solid/src/sidebar/feeds/feed-item.tsx
import { UnsubscribeAlert } from './unsubscribe-alert'
import type { Feed } from '@colette/core'
import { A } from '@solidjs/router'
import MoreHorizontal from 'lucide-solid/icons/more-horizontal'
import { type Component, createSignal } from 'solid-js'
import { Favicon } from '~/components/favicon'
import { AlertDialog, AlertDialogTrigger } from '~/components/ui/alert-dialog'
import { Badge } from '~/components/ui/badge'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '~/components/ui/dropdown-menu'
import {
  SidebarMenuAction,
  SidebarMenuButton,
  SidebarMenuItem,
} from '~/components/ui/sidebar'

export const FeedItem: Component<{ feed: Feed }> = (props) => {
  const [isAlertOpen, setAlertOpen] = createSignal(false)

  return (
    <SidebarMenuItem>
      <SidebarMenuButton
        as={A}
        class="justify-between"
        href={`/feeds/${props.feed.id}`}
      >
        <div class="flex items-center gap-2">
          <Favicon url={props.feed.link} />
          {props.feed.title ?? props.feed.originalTitle}
        </div>
        {props.feed.unreadCount && (
          <Badge class="justify-self-end" variant="outline">
            {props.feed.unreadCount}
          </Badge>
        )}
      </SidebarMenuButton>
      <AlertDialog open={isAlertOpen()} onOpenChange={setAlertOpen}>
        <DropdownMenu placement="right-start">
          <DropdownMenuTrigger as={SidebarMenuAction<'button'>}>
            <MoreHorizontal />
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <AlertDialogTrigger as={DropdownMenuItem<'div'>}>
              Unsubscribe
            </AlertDialogTrigger>
          </DropdownMenuContent>
        </DropdownMenu>
        <UnsubscribeAlert feed={props.feed} close={() => setAlertOpen(false)} />
      </AlertDialog>
    </SidebarMenuItem>
  )
}

// apps/web/src/routes/feeds/components/feed-item.tsx
import { EditFeedModal } from './edit-feed-modal'
import { Feed } from '@colette/core'
import { ExternalLink, Pencil, Trash2 } from 'lucide-react'
import { FC } from 'react'
import { AlertDialog, Dialog } from '~/components/dialog'
import { Favicon } from '~/components/favicon'
import { AlertDialogTrigger } from '~/components/ui/alert-dialog'
import { Button } from '~/components/ui/button'
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardFooter,
} from '~/components/ui/card'
import { DialogTrigger } from '~/components/ui/dialog'
import { UnsubscribeAlert } from '~/sidebar/library/feeds/unsubscribe-alert'

export const FeedItem: FC<{ feed: Feed }> = (props) => {
  return (
    <Card key={props.feed.id} className="flex items-center justify-between">
      <CardHeader>
        <CardTitle>{props.feed.title}</CardTitle>
        <CardDescription className="flex items-center gap-2">
          <Favicon url={props.feed.link} />
          {new URL(props.feed.link).hostname}
        </CardDescription>
      </CardHeader>
      <CardFooter className="p-3">
        <Button asChild variant="ghost">
          <a href={props.feed.link} target="_blank" rel="noreferrer">
            <ExternalLink />
          </a>
        </Button>
        <Dialog>
          {(close) => (
            <>
              <DialogTrigger asChild>
                <Button variant="ghost">
                  <Pencil />
                </Button>
              </DialogTrigger>
              <EditFeedModal feed={props.feed} close={close} />
            </>
          )}
        </Dialog>
        <AlertDialog>
          {(close) => (
            <>
              <AlertDialogTrigger asChild>
                <Button variant="ghost">
                  <Trash2 />
                </Button>
              </AlertDialogTrigger>
              <UnsubscribeAlert feed={props.feed} close={close} />
            </>
          )}
        </AlertDialog>
      </CardFooter>
    </Card>
  )
}
