// packages/app/src/auth-layout.tsx
import { useAPI } from './lib/api-context'
import { AppSidebar } from './sidebar'
import { getActiveOptions } from '@colette/query'
import {
  SidebarProvider,
  SidebarTrigger,
} from '@colette/react-ui/components/ui/sidebar'
import { useQuery } from '@tanstack/react-query'
import { type FC, type PropsWithChildren, useEffect } from 'react'
import { useLocation } from 'wouter'

export const AuthLayout: FC<PropsWithChildren> = (props) => {
  const api = useAPI()
  const [, navigate] = useLocation()

  const { data, isLoading } = useQuery({
    ...getActiveOptions(api),
    retry: false,
  })

  useEffect(() => {
    if (!isLoading && !data) {
      navigate(
        `/login?redirect=${encodeURIComponent(window.location.pathname)}`,
        {
          replace: true,
        },
      )
    }
  }, [isLoading, data, navigate])

  if (isLoading || !data) return

  return (
    <SidebarProvider>
      <>
        <AppSidebar user={data} />
        <div className="w-full">
          <SidebarTrigger />
          {props.children}
        </div>
      </>
    </SidebarProvider>
  )
}

// apps/solid/src/auth-layout.tsx
import { getActiveOptions } from '@colette/solid-query'
import { useNavigate } from '@solidjs/router'
import { createQuery } from '@tanstack/solid-query'
import { type ParentComponent, Show, createEffect } from 'solid-js'
import { SidebarProvider, SidebarTrigger } from './components/ui/sidebar'
import { useAPI } from './lib/api-context'
import { AppSidebar } from './sidebar'

export const AuthLayout: ParentComponent = (props) => {
  const api = useAPI()
  const navigate = useNavigate()

  const query = createQuery(() => ({
    ...getActiveOptions(api),
    retry: false,
  }))

  createEffect(() => {
    if (!query.isLoading && !query.data) {
      navigate(
        `/login?redirect=${encodeURIComponent(window.location.pathname)}`,
        {
          replace: true,
        },
      )
    }
  })

  return (
    <SidebarProvider>
      <Show when={query.isLoading ? undefined : query.data}>
        {(user) => (
          <>
            <AppSidebar user={user()} />
            <div class="w-full">
              <SidebarTrigger />
              {props.children}
            </div>
          </>
        )}
      </Show>
    </SidebarProvider>
  )
}
