// packages/web/src/main.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import './index.css'
import { HttpAPI } from '@colette/core'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { ThemeProvider } from './components/theme-provider'
import { routeTree } from './routeTree.gen'

const queryClient = new QueryClient()
const api = new HttpAPI({
  baseUrl: import.meta.env.DEV ? import.meta.env.VITE_BACKEND_URL : '',
  credentials: 'include',
})

const router = createRouter({
  routeTree,
  context: {
    queryClient,
    api,
  },
  defaultPreload: 'intent',
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <ThemeProvider>
      <QueryClientProvider client={queryClient}>
        <RouterProvider router={router} />
      </QueryClientProvider>
    </ThemeProvider>
  </React.StrictMode>,
)

// apps/solid/src/index.tsx
/* @refresh reload */
import App from './App'
import './index.css'
import { APIProvider } from './lib/api-context'
import { ThemeProvider } from './lib/theme-context'
import { HttpAPI } from '@colette/core'
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query'
import { render } from 'solid-js/web'

const root = document.getElementById('root')

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    'Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?',
  )
}

const api = new HttpAPI({
  baseUrl: import.meta.env.DEV ? import.meta.env.VITE_BACKEND_URL : '/api/v1',
  credentials: 'include',
})
const client = new QueryClient()

render(() => {
  return (
    <>
      <ThemeProvider>
        <QueryClientProvider client={client}>
          <APIProvider api={api}>
            <App />
          </APIProvider>
        </QueryClientProvider>
      </ThemeProvider>
    </>
  )
}, root!)
