// apps/web/src/routes/login/components/login-form.tsx
import { useLoginMutation } from '@colette/query'
import { useForm } from '@tanstack/react-form'
import type { FC } from 'react'
import { z } from 'zod'
import { FormMessage } from '~/components/form'
import { Button } from '~/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '~/components/ui/card'
import { Input } from '~/components/ui/input'
import { Label } from '~/components/ui/label'

export const LoginForm: FC = () => {
  const form = useForm({
    defaultValues: {
      email: '',
      password: '',
    },
    onSubmit: ({ value }) =>
      login.mutate(value, {
        onSuccess: () => form.reset(),
      }),
  })

  const login = useLoginMutation()

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault()
        form.handleSubmit()
      }}
    >
      <Card>
        <CardHeader>
          <CardTitle>Login</CardTitle>
          <CardDescription>Login to your account</CardDescription>
        </CardHeader>
        <CardContent className="space-y-2">
          <form.Field
            name="email"
            validators={{
              onBlur: z.string().email('Please enter a valid email'),
            }}
          >
            {(field) => (
              <div className="space-y-1">
                <Label>Email</Label>
                <Input
                  type="email"
                  value={field.state.value}
                  placeholder="user@example.com"
                  onChange={(e) => field.handleChange(e.target.value)}
                  onBlur={field.handleBlur}
                />
                <FormMessage>
                  {field.state.meta.errors[0]?.toString()}
                </FormMessage>
              </div>
            )}
          </form.Field>
          <form.Field
            name="password"
            validators={{
              onBlur: z
                .string()
                .min(8, 'Password must be at least 8 characters'),
            }}
          >
            {(field) => (
              <div className="space-y-1">
                <Label>Password</Label>
                <Input
                  type="password"
                  value={field.state.value}
                  placeholder="********"
                  onChange={(e) => field.handleChange(e.target.value)}
                  onBlur={field.handleBlur}
                />
                <FormMessage>
                  {field.state.meta.errors[0]?.toString()}
                </FormMessage>
              </div>
            )}
          </form.Field>
        </CardContent>
        <CardFooter>
          <Button className="flex-1" disabled={login.isPending}>
            Login
          </Button>
        </CardFooter>
      </Card>
    </form>
  )
}

// apps/solid/src/login/login-form.tsx
import { loginOptions } from '@colette/solid-query'
import { createForm } from '@tanstack/solid-form'
import { createMutation, useQueryClient } from '@tanstack/solid-query'
import type { Component } from 'solid-js'
import { z } from 'zod'
import { useAPI } from '~/lib/api-context'
import { Button } from '~/lib/components/button'
import {
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardRoot,
  CardTitle,
} from '~/lib/components/card'
import { FormControl, FormMessage } from '~/lib/components/form'
import { Input } from '~/lib/components/input'
import { Label } from '~/lib/components/label'

export const LoginForm: Component = () => {
  const form = createForm(() => ({
    defaultValues: {
      email: '',
      password: '',
    },
    onSubmit: ({ value }) => login(value),
  }))

  const { mutateAsync: login, isPending } = createMutation(() =>
    loginOptions(
      {
        onSuccess: async (user) => {
          console.log(user)

          form.reset()
        },
      },
      useAPI(),
      useQueryClient(),
    ),
  )

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault()
        form.handleSubmit()
      }}
    >
      <CardRoot>
        <CardHeader class="space-y-2">
          <CardTitle>Login</CardTitle>
          <CardDescription>Login to your account</CardDescription>
        </CardHeader>
        <CardContent class="space-y-4">
          <form.Field
            name="email"
            validators={{
              onBlur: z.string().email('Email is not valid'),
            }}
          >
            {(field) => (
              <FormControl invalid={field().state.meta.errors.length > 0}>
                <Label>Email</Label>
                <Input
                  placeholder="user@email.com"
                  onChange={(e) => field().handleChange(e.target.value)}
                  onBlur={() => field().handleBlur()}
                />
                <FormMessage>
                  {field().state.meta.errors[0]?.toString()}
                </FormMessage>
              </FormControl>
            )}
          </form.Field>
          <form.Field
            name="password"
            validators={{
              onBlur: z
                .string()
                .min(8, 'Password must be at least 8 characters'),
            }}
          >
            {(field) => (
              <FormControl invalid={field().state.meta.errors.length > 0}>
                <Label>Password</Label>
                <Input
                  type="password"
                  placeholder="********"
                  onChange={(e) => field().handleChange(e.target.value)}
                  onBlur={() => field().handleBlur()}
                />
                <FormMessage>
                  {field().state.meta.errors[0]?.toString()}
                </FormMessage>
              </FormControl>
            )}
          </form.Field>
        </CardContent>
        <CardFooter>
          <Button class="grow" disabled={isPending}>
            Login
          </Button>
        </CardFooter>
      </CardRoot>
    </form>
  )
}
