// packages/app/lib/sidebar/collections/collection-list.tsx
import { CollectionItem } from './collection-item'
import { listCollectionsOptions } from '@colette/query'
import { Sidebar } from '@colette/ui'
import { useQuery } from '@tanstack/react-query'

export const CollectionList = () => {
  const query = useQuery(listCollectionsOptions())

  if (query.isLoading || !query.data) return

  return (
    <Sidebar.Menu>
      {query.data.data.map((collection) => (
        <CollectionItem key={collection.id} collection={collection as never} />
      ))}
    </Sidebar.Menu>
  )
}

// apps/solid/src/sidebar/collection-list.tsx
import { listCollectionsOptions } from '@colette/solid-query'
import { createQuery } from '@tanstack/solid-query'
import { type Component, For, Show } from 'solid-js'
import { useAPI } from '~/lib/api-context'
import { CollectionItem } from './collection-item'

export const CollectionList: Component = () => {
  const query = createQuery(() => listCollectionsOptions(useAPI()))

  return (
    <Show when={query.data}>
      {(collections) => (
        <For each={collections().data}>
          {(item) => <CollectionItem collection={item} />}
        </For>
      )}
    </Show>
  )
}
