// apps/web/src/sidebar/collections/collection-list.tsx
import { CollectionItem } from './collection-item'
import { listCollectionsOptions } from '@colette/query'
import { useAPI } from '@colette/util'
import { useQuery } from '@tanstack/react-query'
import type { FC } from 'react'

export const CollectionList: FC = () => {
  const api = useAPI()

  const { data: collections, isLoading } = useQuery(listCollectionsOptions(api))

  if (isLoading || !collections) return

  return collections.data.map((collection) => (
    <CollectionItem key={collection.id} collection={collection} />
  ))
}

// apps/solid/src/sidebar/collection-list.tsx
import { listCollectionsOptions } from '@colette/solid-query'
import { createQuery } from '@tanstack/solid-query'
import { type Component, For, Show } from 'solid-js'
import { useAPI } from '~/lib/api-context'
import { CollectionItem } from './collection-item'

export const CollectionList: Component = () => {
  const query = createQuery(() => listCollectionsOptions(useAPI()))

  return (
    <Show when={query.data}>
      {(collections) => (
        <For each={collections().data}>
          {(item) => <CollectionItem collection={item} />}
        </For>
      )}
    </Show>
  )
}
