// apps/solid/src/routes/collections/bookmark-grid.tsx
import { listBookmarksOptions } from '@colette/solid-query'
import { createInfiniteQuery } from '@tanstack/solid-query'
import { type Component, For, onCleanup, onMount } from 'solid-js'
import { useAPI } from '~/lib/api-context'
import { BookmarkCard } from './bookmark-card'

export const BookmarkGrid: Component<{
  collectionId?: string
}> = (props) => {
  const api = useAPI()

  const query = createInfiniteQuery(() =>
    listBookmarksOptions({ collectionId: props.collectionId }, api),
  )

  let target: HTMLDivElement | undefined

  onMount(() => {
    const observer = new IntersectionObserver(
      async (entries) => {
        if (entries.at(0)?.isIntersecting && query.hasNextPage) {
          query.fetchNextPage()
        }
      },
      {
        rootMargin: '200px',
      },
    )

    if (target) {
      observer.observe(target)
    }

    onCleanup(() => {
      if (target) {
        observer.unobserve(target)
      }
    })
  })

  return (
    <div class="space-y-8 px-8 pb-8">
      <div class="grid grid-cols-3 gap-4">
        <For
          each={query.data?.pages.flatMap((page) => page.data)}
          fallback={
            <div class="text-muted-foreground">
              No bookmarks in this collection.
            </div>
          }
        >
          {(item) => <BookmarkCard bookmark={item} />}
        </For>
      </div>
      <div ref={target} class="sr-only" />
    </div>
  )
}

// apps/web/src/routes/bookmarks/components/bookmark-grid.tsx
import { BookmarkCard } from './bookmark-card'
import type { Bookmark } from '@colette/core'
import { listBookmarksOptions } from '@colette/query'
import { useAPI } from '@colette/util'
import { useIntersectionObserver } from '@colette/util'
import { useInfiniteQuery } from '@tanstack/react-query'
import type { FC } from 'react'

export const BookmarkGrid: FC<{
  created?: Bookmark
}> = (props) => {
  const api = useAPI()

  const { data, isLoading, hasNextPage, fetchNextPage } = useInfiniteQuery(
    listBookmarksOptions(api),
  )

  const target = useIntersectionObserver({
    options: {
      rootMargin: '200px',
    },
    onChange: (isIntersecting) =>
      isIntersecting && hasNextPage && fetchNextPage,
  })

  if (isLoading || !data) return

  const bookmarks = data.pages.flatMap((page) => page.data)

  const filtered = props.created
    ? bookmarks.filter((v) => v.id !== props.created?.id)
    : bookmarks

  return (
    <div className="grid grid-cols-1 gap-4 px-8 pb-8 md:grid-cols-2 lg:grid-cols-3">
      {props.created && (
        <div className="rounded-lg border-2">
          <BookmarkCard bookmark={props.created} />
        </div>
      )}
      {filtered.map((bookmark) => (
        <BookmarkCard key={bookmark.id} bookmark={bookmark} />
      ))}
      <div ref={target} />
    </div>
  )
}
